### ISSUE TITLE
Handle Proxy Not Online Error

### ISSUE THREAD

**Issue by adrianmeraz** [adrianmeraz/dj-spoofer#49]
```
[WARNING/MainProcess MainThread] Max tries reached: 4
Traceback (most recent call last):
  File "/home/adrian/.cache/pypoetry/virtualenvs/dj-spoofer-MzYc8ojX-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/adrian/.cache/pypoetry/virtualenvs/dj-spoofer-MzYc8ojX-py3.8/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/adrian/.cache/pypoetry/virtualenvs/dj-spoofer-MzYc8ojX-py3.8/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/home/adrian/.cache/pypoetry/virtualenvs/dj-spoofer-MzYc8ojX-py3.8/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/home/adrian/.cache/pypoetry/virtualenvs/dj-spoofer-MzYc8ojX-py3.8/lib/python3.8/site-packages/httpcore/_sync/http_proxy.py", line 264, in handle_request
    raise ProxyError(msg)
httpcore.ProxyError: 564 Proxy Not Online
```

**Comment by adrianmeraz** [comment]
May use the autoReplace=True param in the proxy url if it resolves the issue

**Comment by adrianmeraz** [comment]
autoReplace=True does not work if ip is down and proxyIp param is used

**Comment by adrianmeraz** [comment]
Now we try to get the newest 3 ip fingerprints. They are validated one by one until a valid one is returned. 

If no valid ip fingerprints are returned, generate a new one from a new ip
