### ISSUE TITLE
Djspoofer ssl_check admin command doesn't work

### ISSUE THREAD

**Issue by adrianmeraz** [adrianmeraz/dj-spoofer#50]
```
(marz-spoofer-TCSbIz7y-py3.8) adrian@adrian:~/PycharmProjects/marz-explorer$ poetry run zappa manage dev "ssl_check"
[START] RequestId: 647b24f4-799f-4649-8113-c66231d552e5 Version: $LATEST
[DEBUG/MainProcess MainThread] Zappa Event: {'manage': 'ssl_check'}
[ERROR] ModuleNotFoundError: No module named 'howsmyssl'
Traceback (most recent call last):
  File "/var/task/handler.py", line 657, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 254, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 432, in handler
    management.call_command(*event["manage"].split(" "))
  File "/var/task/django/core/management/__init__.py", line 113, in call_command
    command = load_command_class(app_name, command_name)
  File "/var/task/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/djspoofer/management/commands/ssl_check.py", line 6, in <module>
    from howsmyssl import howsmyssl_apiEND RequestId: 647b24f4-799f-4649-8113-c66231d552e5
```

**Comment by adrianmeraz** [comment]
Appears that all modules need to be refactored and not imported as apps

**Comment by adrianmeraz** [comment]
Moved all models, managers, and admin commands into djspoofer app

**Comment by adrianmeraz** [comment]
Added many fixes and admin commands now all work
